//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarabi_119.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tarabi_119.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2d_computer_graphics_video_game_character_concept_art_2d_game_character_sprites_c90a3bd8fff52192fe2c8c7cf37499f1 {
            get {
                object obj = ResourceManager.GetObject("2d-computer-graphics-video-game-character-concept-art-2d-game-character-sprites-c" +
                        "90a3bd8fff52192fe2c8c7cf37499f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2d_computer_graphics_video_game_character_concept_art_2d_game_character_sprites_c90a3bd8fff52192fe2c8c7cf3799f1 {
            get {
                object obj = ResourceManager.GetObject("2d-computer-graphics-video-game-character-concept-art-2d-game-character-sprites-c" +
                        "90a3bd8fff52192fe2c8c7cf3799f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AZo6u4T32RK7_FPSIfhpTw_AZo6u4T3_sD7l18wmM9_BQ {
            get {
                object obj = ResourceManager.GetObject("AZo6u4T32RK7-FPSIfhpTw-AZo6u4T3_sD7l18wmM9-BQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AZpOvDHdzW3wxnnMcZNp3Q_AZpOvDHdkTxPLZwsB4likA {
            get {
                object obj = ResourceManager.GetObject("AZpOvDHdzW3wxnnMcZNp3Q-AZpOvDHdkTxPLZwsB4likA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AZpQL6Q8EJSlSSDh97ay7g_AZpQL6Q8nk6f9SyulM3ALA {
            get {
                object obj = ResourceManager.GetObject("AZpQL6Q8EJSlSSDh97ay7g-AZpQL6Q8nk6f9SyulM3ALA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AZpQL6Q8EJSlSSDh97ay7g_AZpQL6Q8nk6f9SyulM3ALA_fotor_bg_remover_20251104225647 {
            get {
                object obj = ResourceManager.GetObject("AZpQL6Q8EJSlSSDh97ay7g-AZpQL6Q8nk6f9SyulM3ALA-fotor-bg-remover-20251104225647", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AZpQL6Q8EJSlSSDh97ay7g_AZpQL6Q8nk6f9SyulM3ALA_fotor_bg_remover_20251104225722 {
            get {
                object obj = ResourceManager.GetObject("AZpQL6Q8EJSlSSDh97ay7g-AZpQL6Q8nk6f9SyulM3ALA-fotor-bg-remover-20251104225722", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_arrow_key_64__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-arrow-key-64 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_arrow_keys_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-arrow-keys-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_arrow_keys_64__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-arrow-keys-64 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_arrow_keys_64__1_1 {
            get {
                object obj = ResourceManager.GetObject("icons8-arrow-keys-64 (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_arrow_keys_6w4__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-arrow-keys-6w4 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_pixel_art_start_button_text_logo_number_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-pixel-art-start-button-text-logo-number-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_pixel_art_start_button_text_logo_number_thumbnail1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-pixel-art-start-button-text-logo-number-thumbnail1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg {
            get {
                object obj = ResourceManager.GetObject("pngegg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__1_ {
            get {
                object obj = ResourceManager.GetObject("pngegg (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
